// Real data extracted from INCOA AP Vendor Tracker v14 (March 27, 2026)

export const SEED_LEVERAGE_DATA = {
  currentValue: 2770713,
  unit: '$',
  trend: 'increasing',
  change: +158259,
  changePeriod: 'Tier 1 urgent',
  sparkline: [158259, 152291, 1834096, 626067],
  sparklineLabels: ['Act Now', 'Unblock', 'Monitor', 'Pay Later'],
  threshold: { warning: 2000000, critical: 3000000 },
  context: 'Total AP owed across 191 vendors (excl. Belfond). Tier 1 urgent: $158K across 5 vendors requiring immediate action.',
  breakdown: [
    { name: 'Tier 1 — Act Now', value: 158259 },
    { name: 'Tier 2 — Unblock', value: 152291 },
    { name: 'Tier 3 — Monitor', value: 1834096 },
    { name: 'Tier 4 — Pay Later', value: 626067 },
  ],
};

export const SEED_COMPARISON_DATA = {
  entities: [
    {
      name: 'Acme-Hardesty',
      metrics: {
        balance: '$81,747',
        tier: 'Tier 1 — Act Now',
        daysSilent: '22d',
        emails: '24',
        escalation: 'Legal + Collections',
        risk: 'Raw Materials (Chemicals)',
      },
    },
    {
      name: 'Vac2Go',
      metrics: {
        balance: '$37,220',
        tier: 'Tier 1 — Act Now',
        daysSilent: '10d',
        emails: '45',
        escalation: 'Legal + Collections',
        risk: 'Environmental Services',
      },
    },
  ],
  highlights: [
    { metric: 'balance', insight: 'Acme-Hardesty owes 2.2x more than Vac2Go but has a payment plan in progress' },
    { metric: 'escalation', insight: 'Both vendors have escalated to legal action and collections referral' },
  ],
};

export const SEED_ALERT_DATA = {
  alerts: [
    {
      id: 'a1',
      severity: 'high' as const,
      title: 'Vac2Go — $37,220',
      description: 'INCOA\'s new CFO Holly Johnson emailed Don Pulford on 3/17/2026: \'I am the new CFO at Incoa and I have been here a little under 1 month. I am meeting with the Ops team today at 11am and should have a response for you this afternoon.\' Vac2Go had reques',
      timestamp: Date.now() - 864000000,
      actionable: true,
    },
    {
      id: 'a2',
      severity: 'high' as const,
      title: 'Delta Ducon LLC (Natalie Newnom) — $27,831',
      description: 'Natalie Newnom (Delta Ducon LLC) sent 3rd request on 3/10/2026 for Invoice 4839 ($27,830.80), now 52 days past due. Escalated to David Difo and Wendy Childs: \'This will affect any pending project and puts customer in pre pay status after 60 days and ',
      timestamp: Date.now() - 1468800000,
      actionable: true,
    },
    {
      id: 'a3',
      severity: 'high' as const,
      title: 'Coverall Service — $7,624',
      description: 'Letitia Davis (Franchise Advisor) sent formal suspension notice: \'Due to non-payment of your outstanding balance of $3,912.00, Coverall will suspend janitorial services effective March 31, 2026, unless payment is received in full no later than March ',
      timestamp: Date.now() - 86400000,
      actionable: true,
    },
    {
      id: 'a4',
      severity: 'high' as const,
      title: 'McGriff Tire (JoAnne Dunagan) — $3,837',
      description: 'McGriff Tire credit dept. Jo Dunagan\'s follow-up on 3/17/2026: \'I am following up on the two past due invoices that we discussed and I emailed you about on 03/04/2026... The invoices were due in September and October. The account is currently locked ',
      timestamp: Date.now() - 864000000,
      actionable: true,
    },
    {
      id: 'a5',
      severity: 'high' as const,
      title: 'Acme-Hardesty — $81,747',
      description: 'Vendor\'s Senior Controller Brittany VanGilder emailed on 3/5/2026 requesting urgent update on payment plan for SINV054091 ($40,873.29) and SINV054256 ($40,873.28): \'Without communication and progress toward the past due balances, we will proceed with',
      timestamp: Date.now() - 1900800000,
      actionable: true,
    },
    {
      id: 'a6',
      severity: 'medium' as const,
      title: 'White Oak Logistics — $52,520',
      description: 'Highly active vendor (50 emails). Most recent exchange 3/23/2026: Holly Johnson (new CFO) gave her number (251-610-8708) and White Oak\'s Luke Hughes confirmed their CFO Chandra Johnson would call the next afternoon. Payments over 100-200 days old hav',
      timestamp: Date.now() - 345600000,
      actionable: true,
    },
    {
      id: 'a7',
      severity: 'medium' as const,
      title: 'Power & Rubber Supply (Carrie Fendley) — $50,953',
      description: 'Power & Rubber Supply AR. Last email 2/12/2026: Carrie said INCOA maintenance placed an order and claimed payment was coming that week. She cleared the order but warned: \'pickup/delivery of that order will be contingent on receiving that payment. Onc',
      timestamp: Date.now() - 259200000,
      actionable: true,
    },
    {
      id: 'a8',
      severity: 'medium' as const,
      title: 'EquipmentShare — $34,579',
      description: 'Angie Hobbs emailed 3/4/2026: 4 invoices totaling $9,418.04 highlighted in red needing payment, last payment received Dec 2025. \'To keep the account from being placed on hold for rentals, please provide a payment status for all past due invoices by W',
      timestamp: Date.now() - 1987200000,
      actionable: true,
    },
    {
      id: 'a9',
      severity: 'medium' as const,
      title: 'D.W. Prouty Co. — $6,395',
      description: 'D.W. Prouty sent 3rd request on 2/6/2026 for invoice DWP/2025/02733 ($6,394.56 due 11/28/2025): \'We have made several attempts to obtain payment with no response or answered messages. Your account is on Credit Hold.\' Lyn Smith followed up again on 2/',
      timestamp: Date.now() - 3110400000,
      actionable: true,
    },
    {
      id: 'a10',
      severity: 'medium' as const,
      title: 'Sunbelt Rentals — $6,015',
      description: 'Donna Spencer emailed 3/6/2026: \'No payment has been made in 4 months on your account.\' Total past due is $6,095.70 across 6 scaffolding invoices plus late charges dating back to Nov 2025. Late charges now accruing ($33.25 in Jan, $47.49 in Feb). Ear',
      timestamp: Date.now() - 1814400000,
      actionable: true,
    },
    {
      id: 'a11',
      severity: 'medium' as const,
      title: 'Videojet Technologies — $1,830',
      description: 'Smarak Sahoo emailed on 3/17/2026 (subject: \'ACCOUNT ON HOLD\'): Invoice #4440986 ($853.67, due 2/22/2026) now 29 days past terms, plus a new Invoice #4491677 ($381.99). \'Terms on future orders will be impacted by continued delinquency.\' An automated ',
      timestamp: Date.now() - 86400000,
      actionable: true,
    }
  ],
};

export const SEED_INSPECTOR_DATA = {
  columns: ['Vendor', 'Balance', 'Tier', 'Last Contact', 'Category', 'Status'],
  rows: [
    ['CSX Transportation', '$523,216', 'Monitor', '217d', 'Logistics/Shipping (Rail Freig', 'Active'],
    ['Alabama Power (Southern Company)', '$256,553', 'Monitor', '37d', 'Utility (Electricity) — Operat', 'Active'],
    ['Millard Maritime, LLC', '$226,306', 'Monitor', '—', 'Logistics/Shipping (Maritime)', 'Active'],
    ['AITX (Julie Momany)', '$158,353', 'Monitor', '391d', 'Production Equipment/Technolog', 'Active'],
    ['Mittal Technopack (Aran Group)', '$113,903', 'Monitor', '108d', 'Packaging — Production Critica', 'Active'],
    ['Blake & Pendleton', '$98,188', 'Monitor', '53d', 'Logistics/Shipping; Raw Materi', 'Active'],
    ['Acme-Hardesty', '$81,747', 'Act Now', '22d', 'Raw Materials (Chemicals) — Pr', 'Watch'],
    ['Harry W. Gaffney & Co. (Karen Reese)', '$78,572', 'Monitor', '23d', 'Professional Services (Account', 'Active'],
  ],
};

export const SEED_BRIEF_DATA = {
  title: 'AP Risk Assessment — INCOA Performance Minerals',
  generatedAt: Date.now(),
  content: `Total accounts payable stands at $2.77M across 191 vendors. Five Tier 1 vendors ($158K) require immediate action:

**Acme-Hardesty ($81,747)**: Payment plan partially working — 1 of 3 installments paid. Collections threat by March 11 if no progress. Raw materials supplier — production critical.

**Vac2Go ($37,220)**: 45 emails over 426 days. Escalated to legal and collections. New CFO Holly Johnson made contact 3/17. Environmental services vendor with equipment on-site.

**Delta Ducon ($27,831)**: Lien filing threatened after 60 days. No INCOA response. Dust collection equipment — production dependency.

**Coverall Service ($7,624)**: Janitorial suspension effective March 31 unless $3,912 paid by March 27. Facility operations at risk.

**McGriff Tire ($3,837)**: Account locked to credit purchases. Safety/regulatory equipment supplier.

Tier 3 contains the largest dollar exposure ($1.83M) led by CSX Transportation ($523K — rail freight, no payments in 90 days) and Alabama Power ($257K — $100K reconnect deposit risk).`,
  confidence: 0.95,
  sources: ['QuickBooks AP Aging (3/26/2026)', 'Vendor Email Analysis', 'Payment History Cross-Reference'],
};

export const SEED_TIMELINE_DATA = {
  events: [
    { id: 't1', timestamp: Date.now() - 86400000, type: 'system', content: 'Coverall Service suspension deadline: March 27 — $3,912 payment required' },
    { id: 't2', timestamp: Date.now() - 864000000, type: 'user', content: 'CFO Holly Johnson contacted Vac2Go (Don Pulford) — first response in 426 days' },
    { id: 't3', timestamp: Date.now() - 1468800000, type: 'system', content: 'Delta Ducon lien filing warning: 60-day threshold approaching on Invoice 4839' },
    { id: 't4', timestamp: Date.now() - 1900800000, type: 'ai', content: 'Acme-Hardesty collections deadline passed (March 11) — 1 of 3 installments paid, 2 remaining' },
    { id: 't5', timestamp: Date.now() - 5184000000, type: 'system', content: 'Alabama Power disconnect risk: $100K reconnect deposit if any payment missed' },
    { id: 't6', timestamp: Date.now() - 7776000000, type: 'ai', content: 'CSX Transportation identified as largest unpaid vendor — $523K with $0 paid in 90 days' },
  ],
};

export const SEED_DOCUMENT_DATA = {
  fileName: 'INCOA AP Vendor Tracker v14.xlsx',
  summary: 'Consolidated view of all outstanding vendor payables for INCOA Performance Minerals, reconciled against QuickBooks aging and vendor email communications. Total AP of $2.77M across 191 vendors with 5 Tier 1 urgent vendors requiring immediate action totaling $158K.',
  paragraphs: [
    'The INCOA AP Vendor Tracker v14 (as of March 27, 2026) provides a consolidated view of all outstanding vendor payables, reconciled against QuickBooks aging and vendor email communications. Designed for CFO-level triage of vendor risk, payment prioritization, and operational exposure.',
    'Total AP owed (excluding Belfond) is $2,770,713 across 191 vendors. Tier 1 (Act Now) contains 5 vendors totaling $158,259 with active legal threats, lien filings, or service suspensions. Tier 2 (Unblock) has 6 vendors at $152,291 with credit holds blocking operations.',
    'Tier 3 (Monitor) represents the largest dollar exposure at $1,834,096 across 19 vendors. CSX Transportation leads at $523,216 with no payments made in 90 days despite being the single largest vendor. Alabama Power at $256,553 carries a $100,000 reconnect deposit risk if payments are missed.',
    'Tier 4 (Pay Later) contains 161 vendors totaling $626,067. These vendors have lower urgency but include some with growing balances, such as Seasons Transport ($61,422) and Chicago Freight Car ($46,780).',
    'Key escalation patterns across all tiers include legal action threats, lien filings, service termination notices, collections referrals, and credit holds/COD requirements. Multiple vendors have received zero responses from INCOA despite repeated outreach.',
    'Data sources include QuickBooks AP Aging Report (3/26/2026), AI-assisted analysis of vendor email communications, and payment history cross-referencing for reconciliation. Amounts flagged "REVIEW" require manual verification.',
  ],
};

export const CANONICAL_DATASET = {
  columns: ['Vendor', 'Priority Tier', 'Balance', 'Days Silent', 'Emails', 'Risk Category', 'Contact'],
  rows: [
    ['CSX Transportation', 'Tier 3 — Monitor', '$523,216', '217', '14', 'Logistics/Shipping (Rail Freight) — Oper', 'CSXT_CashApp; Cabay, Brad; Daniell, Rachel'],
    ['Alabama Power (Southern Company)', 'Tier 3 — Monitor', '$256,553', '37', '43', 'Utility (Electricity) — Operations Criti', 'G2alabamapps@southernco.com'],
    ['Millard Maritime, LLC', 'Tier 3 — Monitor', '$226,306', '—', '3', 'Logistics/Shipping (Maritime)', 'Millard Maritime, LLC'],
    ['AITX (Julie Momany)', 'Tier 3 — Monitor', '$158,353', '391', '1', 'Production Equipment/Technology', 'Julie Momany'],
    ['Mittal Technopack (Aran Group)', 'Tier 3 — Monitor', '$113,903', '108', '20', 'Packaging — Production Critical', 'MTPL-Export; anupammitra@aran-group.com'],
    ['Blake & Pendleton', 'Tier 3 — Monitor', '$98,188', '53', '15', 'Logistics/Shipping; Raw Materials', 'Blake & Pendleton Accounts Receivable'],
    ['Acme-Hardesty', 'Tier 1 — Act Now', '$81,747', '22', '24', 'Raw Materials (Chemicals) — Production C', 'Nancy Rodriguez'],
    ['Harry W. Gaffney & Co. (Karen Reese)', 'Tier 3 — Monitor', '$78,572', '23', '3', 'Professional Services (Accounting/Audit)', 'Karen Reese'],
    ['J.M. Tank Lines', 'Tier 3 — Monitor', '$77,957', '79', '1', 'Logistics/Shipping; Raw Materials', 'Lauren Jackson'],
    ['Christian Pfeiffer (Ruth Schulte)', 'Tier 3 — Monitor', '$67,228', '—', '1', 'Production Equipment (Classification) — ', 'Schulte,Ruth'],
    ['Mondi Group', 'Tier 3 — Monitor', '$67,202', '181', '1', 'Packaging — Production Critical', 'Vazquez Judy (US, Romeoville)'],
    ['Sheppard SVS', 'Tier 3 — Monitor', '$65,286', '256', '4', 'Production Equipment (Motors) — Producti', 'Accounting'],
    ['Seasons Transport (Cindy Williamson)', 'Tier 4 — Pay Later', '$61,422', '193', '6', 'Logistics/Shipping', 'Cindy'],
    ['White Oak Logistics', 'Tier 2 — Unblock', '$52,520', '4', '40', 'Logistics/Shipping; Safety/Regulatory; U', 'Luke Hughes'],
    ['Power & Rubber Supply (Carrie Fendley)', 'Tier 2 — Unblock', '$50,953', '3', '7', 'Logistics/Shipping; Production Equipment', 'Carrie Fendley'],
    ['Chicago Freight Car', 'Tier 4 — Pay Later', '$46,780', '192', '11', 'Logistics/Shipping (Rail Car Leasing)', 'Niaya Ellis'],
    ['Adriana Emmett (company TBD)', 'Tier 4 — Pay Later', '$46,728', '156', '3', 'Logistics/Shipping; Raw Materials; Safet', 'Adriana Emmett'],
    ['Ranger Environmental Services (Tonya Portie)', 'Tier 4 — Pay Later', '$45,092', '134', '5', 'Environmental Services', 'Tonya Portie'],
    ['Zudak Solutions (Carlos Charry)', 'Tier 4 — Pay Later', '$44,986', '53', '9', 'IT/Technology Services', 'Carlos Charry'],
    ['Zudak Solutions LLC', 'Tier 4 — Pay Later', '$44,986', '—', '1', 'Raw Materials; Utility/Operations', 'Zudak Solutions LLC'],
    ['Spire Energy (Gas)', 'Tier 3 — Monitor', '$44,711', '18', '4', 'Utility (Natural Gas) — Operations Criti', 'no-reply@spireenergy.com'],
    ['Cross Country Heating & Cooling', 'Tier 4 — Pay Later', '$38,792', '114', '25', '—', 'Cross Country Heating & Cooling, inc via FreshBooks'],
    ['Vac2Go', 'Tier 1 — Act Now', '$37,220', '10', '45', 'Environmental Services (Vacuum/Cleanup)', 'Don Pulford'],
    ['Bush & Wilton Inc. (Jametta Polk)', 'Tier 4 — Pay Later', '$36,565', '42', '1', 'Industrial Supplies', 'Jametta Polk'],
    ['EquipmentShare', 'Tier 2 — Unblock', '$34,579', '23', '55', 'Equipment Rental — Operations', 'billingreminder@equipmentshare.com'],
    ['Delta Ducon LLC (Natalie Newnom)', 'Tier 1 — Act Now', '$27,831', '17', '3', 'Production Equipment (Dust Collection)', 'Natalie Newnom'],
    ['G.T. Michelli Co.', 'Tier 4 — Pay Later', '$26,544', '39', '21', 'Raw Materials; Safety/Regulatory', 'NetSuite Replies (netsuitereplies@michelli.com)'],
    ['United Rentals', 'Tier 3 — Monitor', '$23,077', '96', '3', 'Equipment Rental — Operations', 'Von Mangornong (UNITED RENTALS); uraccountsreceivable'],
    ['HEPACO / Clean Harbors (Munnawar Mohammed)', 'Tier 4 — Pay Later', '$22,950', '15', '2', 'Raw Materials; Safety/Regulatory; Utilit', 'Mohammed, Munnawar'],
    ['Sterling Systems & Controls (Jackie Davis)', 'Tier 4 — Pay Later', '$15,692', '35', '5', 'Raw Materials; Safety/Regulatory', 'Jackie Davis - Sterling Systems & Controls Inc'],
    ['Grand Quest Industries (GQI)', 'Tier 4 — Pay Later', '$15,424', '11', '17', 'Logistics/Shipping; Packaging/Shipping M', 'Chris Anthony; GQI  Accounts; GQI Accounts'],
    ['Pathfinder Systems Inc', 'Tier 4 — Pay Later', '$14,838', '221', '4', 'Logistics/Shipping; Production Equipment', 'Pathfinder Systems Inc'],
    ['TerraLogic', 'Tier 4 — Pay Later', '$13,970', '40', '24', '—', 'IT Accounting'],
    ['Stem Products (Lem Baldwin)', 'Tier 4 — Pay Later', '$10,200', '123', '7', 'Packaging/Shipping Materials; Raw Materi', 'Lem Baldwin; palletlem'],
    ['McMaster-Carr', 'Tier 4 — Pay Later', '$9,621', '35', '13', 'Logistics/Shipping; Raw Materials; Safet', 'Josh Bolton; McMaster-Carr'],
    ['Coperion', 'Tier 3 — Monitor', '$9,621', '16', '13', 'Production Equipment/Parts; Raw Material', 'Dennis Anand; Dover, Liz; John Balakrishnan, Dennis Anand'],
    ['R.J. Trucking', 'Tier 4 — Pay Later', '$9,038', '23', '24', 'Logistics/Shipping; Production Equipment', 'Mary Jo Testa'],
    ['Brightly Software (Dude Solutions)', 'Tier 4 — Pay Later', '$8,242', '344', '3', 'IT/Technology Services (CMMS)', 'Accounts Receivable; accountsreceivable@brightlysoftware.com'],
    ['Advantage IT Management', 'Tier 4 — Pay Later', '$8,115', '19', '37', 'IT/Technology Services', 'Advantage IT Management Billing Department'],
    ['Coverall Service', 'Tier 1 — Act Now', '$7,624', '-259', '20', 'Facility Services (Janitorial)', 'Reanna Catches'],
    ['Burr & Forman LLP', 'Tier 3 — Monitor', '$7,088', '172', '2', 'Legal / Professional Services', 'macox@burr.com'],
    ['ACC Business Collections Notice RM', 'Tier 4 — Pay Later', '$6,824', '—', '1', '—', 'ACC Business Collections Notice RM'],
    ['D.W. Prouty Co.', 'Tier 2 — Unblock', '$6,395', '36', '6', 'Raw Materials; Utility/Operations', 'Andria Baker'],
    ['Sunbelt Rentals', 'Tier 2 — Unblock', '$6,015', '21', '25', 'Equipment Rental (Scaffolding) — Operati', 'Donna Spencer'],
    ['ALL-PHASE GULFPORT', 'Tier 4 — Pay Later', '$5,733', '—', '1', 'Safety/Regulatory', 'ALL-PHASE GULFPORT'],
    ['Gulf Coast Bearing', 'Tier 3 — Monitor', '$5,139', '31', '3', 'Production Equipment (Bearings) — Produc', 'Kate King'],
    ['NSF International (Maitlin Rifleman)', 'Tier 3 — Monitor', '$5,100', '—', '1', 'Compliance/Certification — NSF food-grad', 'Maitlin Rifleman'],
    ['Tankstar USA', 'Tier 4 — Pay Later', '$4,731', '151', '14', 'Logistics/Shipping; Safety/Regulatory', 'Leslie Kasnia'],
    ['DebtRegister', 'Tier 4 — Pay Later', '$4,439', '—', '4', 'Production Equipment/Parts; Raw Material', 'DebtRegister'],
    ['Cypress Invoicing', 'Tier 4 — Pay Later', '$4,168', '161', '6', '—', 'Cypress Invoicing'],
    ['system@finance.motion.com', 'Tier 4 — Pay Later', '$3,932', '—', '2', 'Raw Materials', 'system@finance.motion.com'],
    ['McGriff Tire (JoAnne Dunagan)', 'Tier 1 — Act Now', '$3,837', '10', '2', 'Raw Materials; Safety/Regulatory', 'JoAnne Dunagan'],
    ['Rev SQL', 'Tier 4 — Pay Later', '$3,740', '254', '4', 'Insurance/Compliance; Raw Materials; Saf', 'Rev SQL'],
    ['CSC Global', 'Tier 4 — Pay Later', '$3,705', '11', '22', 'Production Equipment/Parts; Safety/Regul', 'InvoiceInquiry@cscglobal.com'],
    ['Cintas', 'Tier 4 — Pay Later', '$3,697', '55', '45', 'Safety/Uniforms — Compliance', 'Lopez Campos, Jennifer'],
    ['Uline (via A.G. Adjustments)', 'Tier 4 — Pay Later', '$3,677', '77', '34', 'Logistics/Shipping; Raw Materials; Safet', 'Angel Yzaguirre; Jim Delozier2; info@agaltd.com (info@agaltd.com); Collections Specialists; Loretta Perez; Steve Myers (smyers@agaltd.com)'],
    ['Bureau Veritas', 'Tier 3 — Monitor', '$3,584', '52', '5', 'Insurance/Compliance; Raw Materials; Saf', 'Angela Liquori; BVCERarmail; Judy Gomez'],
    ['Autumn Transport', 'Tier 4 — Pay Later', '$3,500', '9', '42', 'Logistics/Shipping; Raw Materials', 'Mara M. Wyss'],
    ['Susan Elliott', 'Tier 4 — Pay Later', '$3,250', '259', '5', '—', 'Susan Elliott'],
    ['Lease Direct / DLL Financial', 'Tier 4 — Pay Later', '$3,123', '2', '46', 'Equipment Leasing', 'Diego Burgos; LeaseDirect; Pajarillo, A (Angel Shene)'],
    ['HunterLab', 'Tier 3 — Monitor', '$3,013', '64', '4', 'Safety/Regulatory', 'Delnur Turson'],
    ['Peddy, Kerry', 'Tier 4 — Pay Later', '$2,668', '179', '12', 'Raw Materials', 'Peddy, Kerry'],
    ['Prater Industries', 'Tier 4 — Pay Later', '$2,523', '155', '15', 'Production Equipment (Mills) — Productio', 'Ryan Joukema'],
    ['Community Coffee (Veronica Shields)', 'Tier 4 — Pay Later', '$2,337', '77', '2', 'Facility Services (Break Room)', 'Veronica Shields'],
    ['Fluid Engineering Inc.', 'Tier 4 — Pay Later', '$2,274', '31', '8', 'Production Equipment (Dust Collectors) —', 'FEI Customer Receivables'],
    ['Sirius Talent Solutions (via LSQ/eCapital)', 'Tier 4 — Pay Later', '$2,269', '17', '31', 'Staffing/Labor', 'Cherri  Knutson; Ian Rodriguez; May Garcia'],
    ['Haul It Off', 'Tier 4 — Pay Later', '$2,266', '114', '14', 'Logistics/Shipping; Packaging/Shipping M', 'Haul It Off; Jennifer Lillard; haulitoff haulitoffmobile.com'],
    ['Retif Oil & Fuel', 'Tier 4 — Pay Later', '$2,211', '29', '27', 'Logistics/Shipping; Packaging/Shipping M', 'Dianne Scully'],
    ['Genesis Technical Staffing (Rebecca Lumbroso)', 'Tier 4 — Pay Later', '$2,183', '315', '8', 'Staffing/Labor', 'Rebecca Lumbroso'],
    ['Foster, David', 'Tier 4 — Pay Later', '$1,960', '331', '2', 'Logistics/Shipping; Packaging/Shipping M', 'Foster, David'],
    ['BIS Office Systems (Emry Bridges)', 'Tier 4 — Pay Later', '$1,857', '163', '11', 'Office Equipment/Services', 'Emry Bridges'],
    ['Mason, Sabrina', 'Tier 4 — Pay Later', '$1,853', '45', '1', '—', 'Mason, Sabrina'],
    ['DANHART, LLC', 'Tier 4 — Pay Later', '$1,850', '296', '1', 'Production Equipment/Parts; Raw Material', 'DANHART, LLC'],
    ['Videojet Technologies', 'Tier 2 — Unblock', '$1,830', '-8', '27', 'Insurance/Compliance; Logistics/Shipping', 'Sahoo, Smarak'],
    ['Core Business Solutions Accounting', 'Tier 4 — Pay Later', '$1,600', '101', '10', 'Raw Materials', 'Core Business Solutions Accounting'],
    ['TQL Receivables Management', 'Tier 4 — Pay Later', '$1,585', '350', '3', 'Logistics/Shipping; Raw Materials; Safet', 'TQL Receivables Management'],
    ['Uinta Networking Services', 'Tier 4 — Pay Later', '$1,514', '—', '22', 'IT/Technology Services (Network)', 'Uinta Networking Services INC via FreshBooks'],
    ['Olivia Riek (company TBD)', 'Tier 4 — Pay Later', '$1,361', '-23', '10', 'Packaging/Shipping Materials; Production', 'Olivia Riek'],
    ['Tennant Company', 'Tier 4 — Pay Later', '$1,345', '190', '5', 'Facility Equipment (Floor Care)', 'Daunheimer, Nick; Howard, Conner; Rasmussen, Mariah'],
    ['donotreply@lantech.com', 'Tier 4 — Pay Later', '$1,318', '—', '1', 'Raw Materials', 'donotreply@lantech.com'],
    ['khimanshu@ups.com', 'Tier 4 — Pay Later', '$1,303', '200', '2', 'Insurance/Compliance; Production Equipme', 'khimanshu@ups.com'],
    ['Samantha Woodward', 'Tier 4 — Pay Later', '$1,237', '116', '7', 'Insurance/Compliance; Raw Materials', 'Samantha Woodward'],
    ['Sabel Steel (Samantha Ware)', 'Tier 4 — Pay Later', '$1,201', '86', '1', 'Raw Materials/Steel', 'Samantha Ware'],
    ['Safety WearHouse', 'Tier 4 — Pay Later', '$1,200', '281', '30', 'Raw Materials; Safety/Regulatory; Utilit', 'Safety WearHouse'],
    ['Benjamin Meriam', 'Tier 4 — Pay Later', '$1,125', '260', '3', 'Logistics/Shipping; Raw Materials; Safet', 'Benjamin Meriam'],
    ['Harcros Chemicals', 'Tier 4 — Pay Later', '$1,022', '220', '9', 'Raw Materials (Chemicals) — Production C', 'Jan Feist; Sarah Stacey; Skye Greene'],
    ['Enviro-Master', 'Tier 4 — Pay Later', '$1,018', '30', '4', 'Facility Services (Cleaning/Hygiene)', 'ARNOREPLY@ENVIRO-MASTER.COM; ARNO_REPLY@enviro-master.com'],
    ['WESCO Gas & Welding (Deborah Norred)', 'Tier 4 — Pay Later', '$1,007', '162', '8', 'Production Equipment/Parts', 'Deborah Norred'],
    ['Randi Elliott', 'Tier 4 — Pay Later', '$1,000', '214', '6', 'Logistics/Shipping', 'Randi Elliott'],
    ['Susan McCurry', 'Tier 4 — Pay Later', '$917', '199', '4', 'Raw Materials; Safety/Regulatory; Utilit', 'Susan McCurry'],
    ['Endress+Hauser', 'Tier 4 — Pay Later', '$888', '456', '3', 'Insurance/Compliance; Raw Materials', 'E+H US Gulf Credit; Gulf Coast Credit - E+H US'],
    ['Betty Jean Manzanilla', 'Tier 4 — Pay Later', '$569', '143', '8', 'Raw Materials; Utility/Operations', 'Betty Jean Manzanilla'],
    ['Raparthi, Akhil', 'Tier 4 — Pay Later', '$525', '231', '2', 'Safety/Regulatory', 'Raparthi, Akhil'],
    ['Stericycle / Shred-it (Eric Nava)', 'Tier 4 — Pay Later', '$520', '—', '2', 'Facility Services (Document Destruction)', 'Eric Nava'],
    ['Blossman Gas', 'Tier 4 — Pay Later', '$512', '28', '8', 'Utility/Operations', 'Blossman Gas'],
    ['PeopleSense / NovaTime (Jim Castellano)', 'Tier 4 — Pay Later', '$457', '22', '8', 'IT/Technology Services (Timekeeping)', 'Jim Castellano'],
    ['DebtCollection', 'Tier 4 — Pay Later', '$440', '154', '2', 'Raw Materials', 'DebtCollection'],
    ['Roc Global (Art Muscio)', 'Tier 4 — Pay Later', '$386', '326', '1', '—', 'Art Muscio'],
    ['customerservice@apegpt.com', 'Tier 4 — Pay Later', '$339', '239', '1', '—', 'customerservice@apegpt.com'],
    ['Jenn Palmer', 'Tier 4 — Pay Later', '$309', '297', '1', 'Insurance/Compliance', 'Jenn Palmer'],
    ['Comcast Business', 'Tier 4 — Pay Later', '$225', '158', '33', 'Utility (Internet/Telecom)', 'ebbeall@comcast.net'],
    ['InvoiceCloud (Utility Payments)', 'Tier 4 — Pay Later', '$147', '29', '4', 'Raw Materials; Safety/Regulatory; Utilit', 'no-reply@invoicecloud.net'],
    ['Waste Oil Collectors, Inc.', 'Tier 4 — Pay Later', '$140', '9', '1', 'Utility/Operations', 'Waste Oil Collectors, Inc.'],
    ['Eco South Services', 'Tier 4 — Pay Later', '$100', '11', '14', 'Environmental Services', 'Rachel Perryman'],
    ['WESCO (Jessica Lewis)', 'Tier 4 — Pay Later', '$5', '200', '4', 'Raw Materials; Utility/Operations', 'Jessica Lewis'],
    ['Sterling Systems & Controls (Jackie Kitchens)', 'Tier 4 — Pay Later', '$0', '15', '1', 'Insurance/Compliance; Logistics/Shipping', 'Jackie Kitchens'],
    ['Jennifer Griffin', 'Tier 4 — Pay Later', '$0', '16', '10', 'Raw Materials', 'Jennifer Griffin'],
    ['Lindberg, Arthur', 'Tier 4 — Pay Later', '$0', '17', '3', 'Raw Materials; Safety/Regulatory; Utilit', 'Lindberg, Arthur'],
    ['J Cannon', 'Tier 4 — Pay Later', '$0', '63', '3', '—', 'J Cannon'],
    ['Holli Smith', 'Tier 4 — Pay Later', '$0', '35', '2', 'Production Equipment/Parts; Raw Material', 'Holli Smith'],
    ['Corey Helper', 'Tier 4 — Pay Later', '$0', '142', '3', 'Insurance/Compliance; Safety/Regulatory;', 'Corey Helper'],
    ['Laurie Johnston', 'Tier 4 — Pay Later', '$0', '155', '8', 'Raw Materials', 'Laurie Johnston'],
    ['Kenyetta Luckett', 'Tier 4 — Pay Later', '$0', '170', '3', 'Logistics/Shipping; Safety/Regulatory', 'Kenyetta Luckett'],
    ['Ramasamy, Mathumathi', 'Tier 4 — Pay Later', '$0', '178', '1', '—', 'Ramasamy, Mathumathi'],
    ['Kathy Walker', 'Tier 4 — Pay Later', '$0', '198', '2', 'Raw Materials', 'Kathy Walker'],
    ['Jan Trammell', 'Tier 4 — Pay Later', '$0', '274', '5', 'Production Equipment/Parts; Safety/Regul', 'Jan Trammell'],
    ['Michael Tinkl', 'Tier 4 — Pay Later', '$0', '304', '3', '—', 'Michael Tinkl'],
    ['UPRR_ACCT_1', 'Tier 4 — Pay Later', '$0', '311', '1', '—', 'UPRR_ACCT_1'],
    ['elisa@mh3printing.com', 'Tier 4 — Pay Later', '$0', '322', '4', 'Safety/Regulatory', 'elisa@mh3printing.com'],
    ['UPRR_ACCT_2', 'Tier 4 — Pay Later', '$0', '324', '1', '—', 'UPRR_ACCT_2'],
    ['Craig Denham', 'Tier 4 — Pay Later', '$0', '336', '1', 'Raw Materials', 'Craig Denham'],
    ['Sharon Vittor', 'Tier 4 — Pay Later', '$0', '353', '1', 'Insurance/Compliance', 'Sharon Vittor'],
    ['Bruce Oakley / Oakley Trucking', 'Tier 4 — Pay Later', '$0', '—', '6', 'Logistics/Shipping', 'Accounts Receivable'],
    ['Christi C', 'Tier 4 — Pay Later', '$0', '—', '2', '—', 'Christi C'],
    ['ITSupport', 'Tier 4 — Pay Later', '$0', '—', '1', 'Raw Materials', 'ITSupport'],
    ['Jeff Edwards', 'Tier 4 — Pay Later', '$0', '—', '1', 'Utility/Operations', 'Jeff Edwards'],
    ['Julia Davis', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Julia Davis'],
    ['Lori Bryant', 'Tier 4 — Pay Later', '$0', '—', '2', 'Safety/Regulatory; Utility/Operations', 'Lori Bryant'],
    ['Melissa Pelkey', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Melissa Pelkey'],
    ['Niki Horak', 'Tier 4 — Pay Later', '$0', '—', '1', 'Production Equipment/Parts; Raw Material', 'Niki Horak'],
    ['RSM Ebner Stolz on behalf of Dorfner Anzaplan GmbH', 'Tier 4 — Pay Later', '$0', '—', '1', 'Raw Materials', 'RSM Ebner Stolz on behalf of Dorfner Anzaplan GmbH'],
    ['Shelby Day', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Shelby Day'],
    ['Stephanie.arnold@quincycompressor.c', 'Tier 4 — Pay Later', '$0', '—', '1', 'Production Equipment/Parts', 'Stephanie.arnold@quincycompressor.c'],
    ['THOMAS FOSTER', 'Tier 4 — Pay Later', '$0', '—', '4', '—', 'THOMAS FOSTER'],
    ['sabrina.mason@thermofisher.com', 'Tier 4 — Pay Later', '$0', '—', '2', '—', 'sabrina.mason@thermofisher.com'],
    ['Hollis Logistics (Robert Karell)', 'Tier 4 — Pay Later', '$0', '7', '6', 'Logistics/Shipping; Production Equipment', 'Robert Karell'],
    ['Miranda McDaniel', 'Tier 4 — Pay Later', '$0', '88', '2', 'Raw Materials', 'Miranda McDaniel'],
    ['Credit Control', 'Tier 4 — Pay Later', '$0', '233', '4', 'Insurance/Compliance; Raw Materials; Saf', 'Credit Control'],
    ['SLY Accounts Receivable', 'Tier 4 — Pay Later', '$0', '241', '7', 'Packaging/Shipping Materials; Raw Materi', 'SLY Accounts Receivable'],
    ['Receivables US', 'Tier 4 — Pay Later', '$0', '282', '3', 'Raw Materials', 'Receivables US'],
    ['Averitt Express (Tina Stout)', 'Tier 4 — Pay Later', '$0', '312', '2', 'Safety/Regulatory', 'Tina Stout'],
    ['Churon Company', 'Tier 4 — Pay Later', '$0', '360', '7', 'Production Equipment/Parts; Raw Material', 'Churon Company; Jerry Churon'],
    ['Kestrel Liner Agencies', 'Tier 4 — Pay Later', '$0', '373', '2', 'Insurance/Compliance; Logistics/Shipping', 'Alexandria Arguedas; Maviley Vega'],
    ['Purchase Order NORAM', 'Tier 4 — Pay Later', '$0', '374', '1', '—', 'Purchase Order NORAM'],
    ['Bayou Fasteners (Donna Hughes)', 'Tier 4 — Pay Later', '$0', '—', '3', '—', 'Donna Hughes'],
    ['GoTo Customer Payment Support', 'Tier 4 — Pay Later', '$0', '—', '6', 'Raw Materials', 'GoTo Customer Payment Support'],
    ['Lee & Hayes Billing Team', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Lee & Hayes Billing Team'],
    ['Ortiz, Isaura', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Ortiz, Isaura'],
    ['Robinson, Frank J', 'Tier 4 — Pay Later', '$0', '—', '1', 'Safety/Regulatory', 'Robinson, Frank J'],
    ['Yassirys Arsenio Olivero Pérez', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Yassirys Arsenio Olivero Pérez'],
    ['Jason Lipperdt', 'Tier 4 — Pay Later', '$0', '18', '2', 'Production Equipment/Parts; Raw Material', 'Jason Lipperdt'],
    ['Hudson Weber', 'Tier 4 — Pay Later', '$0', '29', '4', 'Raw Materials; Safety/Regulatory; Utilit', 'Hudson Weber'],
    ['Brayden Foutz', 'Tier 4 — Pay Later', '$0', '43', '3', 'Logistics/Shipping; Raw Materials', 'Brayden Foutz'],
    ['Joe Jreij', 'Tier 4 — Pay Later', '$0', '45', '1', '—', 'Joe Jreij'],
    ['Rotthoff, Sharon', 'Tier 4 — Pay Later', '$0', '53', '1', 'Raw Materials; Safety/Regulatory; Utilit', 'Rotthoff, Sharon'],
    ['Danny Paganelli', 'Tier 4 — Pay Later', '$0', '59', '1', '—', 'Danny Paganelli'],
    ['Emily M', 'Tier 4 — Pay Later', '$0', '100', '2', 'Logistics/Shipping; Production Equipment', 'Emily M'],
    ['Norfolk Southern Railway', 'Tier 4 — Pay Later', '$0', '134', '26', 'Logistics/Shipping; Raw Materials', 'Coker, Cody C'],
    ['Dawn M Hahn', 'Tier 4 — Pay Later', '$0', '151', '5', 'Raw Materials; Utility/Operations', 'Dawn M Hahn'],
    ['Jodi Ann Saddler', 'Tier 4 — Pay Later', '$0', '154', '3', 'Raw Materials', 'Jodi Ann Saddler'],
    ['Ira Jackson', 'Tier 4 — Pay Later', '$0', '165', '6', '—', 'Ira Jackson'],
    ['Collections@trin.net', 'Tier 4 — Pay Later', '$0', '200', '2', 'Raw Materials', 'Collections@trin.net'],
    ['Anna Stout', 'Tier 4 — Pay Later', '$0', '241', '9', '—', 'Anna Stout'],
    ['alessandro.albini@air-tec.it', 'Tier 4 — Pay Later', '$0', '259', '1', 'Production Equipment/Parts', 'alessandro.albini@air-tec.it'],
    ['aruffo@air-tec.it', 'Tier 4 — Pay Later', '$0', '259', '2', 'Production Equipment/Parts', 'aruffo@air-tec.it'],
    ['caggiano@air-tec.it', 'Tier 4 — Pay Later', '$0', '259', '2', 'Production Equipment/Parts', 'caggiano@air-tec.it'],
    ['Bryan Cook', 'Tier 4 — Pay Later', '$0', '263', '1', '—', 'Bryan Cook'],
    ['Non-Credit Shipment', 'Tier 4 — Pay Later', '$0', '308', '6', 'Logistics/Shipping; Production Equipment', 'Non-Credit Shipment'],
    ['Sean Phillips', 'Tier 4 — Pay Later', '$0', '317', '4', 'Raw Materials', 'Sean Phillips'],
    ['Micah Gilmore', 'Tier 4 — Pay Later', '$0', '318', '2', 'Safety/Regulatory', 'Micah Gilmore'],
    ['Kim Lewis', 'Tier 4 — Pay Later', '$0', '336', '2', 'Raw Materials; Safety/Regulatory', 'Kim Lewis'],
    ['Stewart Amanda', 'Tier 4 — Pay Later', '$0', '337', '2', 'Raw Materials', 'Stewart Amanda'],
    ['Perumalsamy, Aravind', 'Tier 4 — Pay Later', '$0', '346', '2', 'Raw Materials; Safety/Regulatory', 'Perumalsamy, Aravind'],
    ['accounts.receivable.us@vega.com', 'Tier 4 — Pay Later', '$0', '361', '4', 'Safety/Regulatory', 'accounts.receivable.us@vega.com'],
    ['Chemplex (AR)', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'AR'],
    ['Clean Harbors', 'Tier 4 — Pay Later', '$0', '—', '7', 'Safety/Regulatory', 'Clean Harbors Collections Inquiry; collectionsinquiry@cleanharbors.com'],
    ['Elizabeth Day', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'Elizabeth Day'],
    ['Jen Cardwell', 'Tier 4 — Pay Later', '$0', '—', '2', 'Logistics/Shipping; Safety/Regulatory', 'Jen Cardwell'],
    ['Koganti, Sai Akhila', 'Tier 4 — Pay Later', '$0', '—', '1', 'Safety/Regulatory', 'Koganti, Sai Akhila'],
    ['Stephanie Arnold', 'Tier 4 — Pay Later', '$0', '—', '1', 'Production Equipment/Parts', 'Stephanie Arnold'],
    ['Willis, Lakessia', 'Tier 4 — Pay Later', '$0', '—', '1', 'Raw Materials; Utility/Operations', 'Willis, Lakessia'],
    ['accounting@maderbearing.com', 'Tier 4 — Pay Later', '$0', '—', '1', 'Production Equipment/Parts', 'accounting@maderbearing.com'],
    ['deb@customadvanced.com', 'Tier 4 — Pay Later', '$0', '—', '2', 'Raw Materials', 'deb@customadvanced.com'],
    ['wasteoilinc@gmail.com', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'wasteoilinc@gmail.com'],
    ['BDO Account Notification', 'Tier 4 — Pay Later', '$0', '—', '1', '—', 'BDO Account Notification'],
    ['Pricing Communications', 'Tier 4 — Pay Later', '$0', '—', '1', 'Insurance/Compliance; Safety/Regulatory', 'Pricing Communications'],
    ['Sanchez, Nataly Pamela', 'Tier 4 — Pay Later', '$0', '—', '1', 'Safety/Regulatory', 'Sanchez, Nataly Pamela'],
    ['Saia Inc.', 'Tier 4 — Pay Later', '$0', '82', '3', 'Insurance/Compliance; Logistics/Shipping', 'ARStating; arstating@saia.com'],
    ['Cheril McAleer', 'Tier 4 — Pay Later', '$0', '228', '1', '—', 'Cheril McAleer'],
    ['Timothy Davis', 'Tier 4 — Pay Later', '$0', '350', '2', '—', 'Timothy Davis'],
    ['financialservices@grainger.com', 'Tier 4 — Pay Later', '$0', '372', '1', 'Raw Materials', 'financialservices@grainger.com'],
  ],
};

export const DEFAULT_SUGGESTIONS = [
  { id: 's1', label: 'Show AP exposure', query: 'show me total AP exposure', priority: 1 },
  { id: 's2', label: 'What needs action?', query: 'what vendors need immediate action?', priority: 2 },
  { id: 's3', label: 'Open vendor dataset', query: 'show the full vendor dataset', priority: 3 },
];
